
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "States.h"

#include <react/renderer/components/reactnativekeyboardcontroller/EventEmitters.h>
#include <react/renderer/components/reactnativekeyboardcontroller/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook::react {

JSI_EXPORT extern const char KeyboardControllerViewComponentName[];

/*
 * `ShadowNode` for <KeyboardControllerView> component.
 */
using KeyboardControllerViewShadowNode = ConcreteViewShadowNode<
    KeyboardControllerViewComponentName,
    KeyboardControllerViewProps,
    KeyboardControllerViewEventEmitter,
    KeyboardControllerViewState>;

JSI_EXPORT extern const char KeyboardGestureAreaComponentName[];

/*
 * `ShadowNode` for <KeyboardGestureArea> component.
 */
using KeyboardGestureAreaShadowNode = ConcreteViewShadowNode<
    KeyboardGestureAreaComponentName,
    KeyboardGestureAreaProps,
    KeyboardGestureAreaEventEmitter,
    KeyboardGestureAreaState>;

JSI_EXPORT extern const char OverKeyboardViewComponentName[];

/*
 * `ShadowNode` for <OverKeyboardView> component.
 */
using OverKeyboardViewShadowNode = ConcreteViewShadowNode<
    OverKeyboardViewComponentName,
    OverKeyboardViewProps,
    OverKeyboardViewEventEmitter,
    OverKeyboardViewState>;

} // namespace facebook::react
