// swift-tools-version: 6.0
// HAND-WRITTEN split manifest (#3218 S11): this package mixes Swift and
// Objective-C(++) sources, which Swift Package Manager cannot compile in a
// single target. Measured import direction: the ObjC side registers/bridges the
// Swift classes (it imports the generated "-Swift.h"), so the ObjC(++) target
// depends on the Swift target and never the reverse. The bridging header only
// pulled in React/system headers, which the Swift target gets via the React
// headers products ("import React"), so no project-ObjC bridging remains.
import PackageDescription

let reactHeaders: [Target.Dependency] = [
    .product(name: "ReactHeaders", package: "ReactNative"),
    .product(name: "ReactNativeHeaders", package: "ReactNative"),
    .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
    .product(name: "ReactAppHeaders", package: "React-GeneratedCode"),
]

let package = Package(
    name: "ReactNativeKeyboardController",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ReactNativeKeyboardController", targets: ["ReactNativeKeyboardControllerSwift", "ReactNativeKeyboardControllerObjC"]),
    ],
    dependencies: [
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
        .package(name: "React-GeneratedCode", path: "../../../ios"),
    ],
    targets: [
        .target(
            name: "ReactNativeKeyboardControllerSwift",
            dependencies: reactHeaders,
            path: ".",
            exclude: [
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewState.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewState.h",
                "ios/KeyboardController-Bridging-Header.h",
                "ios/KeyboardControllerModule-Header.h",
                "ios/KeyboardControllerModule.mm",
                "ios/events/FocusedInputLayoutChangedEvent.h",
                "ios/events/FocusedInputLayoutChangedEvent.m",
                "ios/events/FocusedInputSelectionChangedEvent.h",
                "ios/events/FocusedInputSelectionChangedEvent.m",
                "ios/events/FocusedInputTextChangedEvent.h",
                "ios/events/FocusedInputTextChangedEvent.m",
                "ios/events/KeyboardMoveEvent.h",
                "ios/events/KeyboardMoveEvent.m",
                "ios/objc/NSObject+SafeKVC.h",
                "ios/objc/NSObject+SafeKVC.m",
                "ios/objc/RCTUIManager+LayoutAnimationManager.h",
                "ios/objc/RCTUIManager+LayoutAnimationManager.m",
                "ios/objc/TextInput+DelegateManager.h",
                "ios/objc/TextInput+DelegateManager.m",
                "ios/views/ClippingScrollViewDecoratorViewManager.h",
                "ios/views/ClippingScrollViewDecoratorViewManager.mm",
                "ios/views/KeyboardBackgroundViewManager.h",
                "ios/views/KeyboardBackgroundViewManager.mm",
                "ios/views/KeyboardControllerView.h",
                "ios/views/KeyboardControllerView.mm",
                "ios/views/KeyboardControllerViewManager.mm",
                "ios/views/KeyboardExtenderManager.h",
                "ios/views/KeyboardExtenderManager.mm",
                "ios/views/KeyboardGestureAreaManager.h",
                "ios/views/KeyboardGestureAreaManager.mm",
                "ios/views/KeyboardToolbarGroupViewManager.h",
                "ios/views/KeyboardToolbarGroupViewManager.mm",
                "ios/views/OverKeyboardViewManager.h",
                "ios/views/OverKeyboardViewManager.mm",
            ],
            sources: [
                      "Package.swift",
                      "ios/KeyboardBackdropController.swift",
                      "ios/KeyboardControllerModuleImpl.swift",
                      "ios/animations/KeyboardAnimation.swift",
                      "ios/animations/SpringAnimation.swift",
                      "ios/animations/TimingAnimation.swift",
                      "ios/core/KeyboardControllerConfiguration.swift",
                      "ios/core/UIUtils.swift",
                      "ios/delegates/KCTextInputCompositeDelegate.swift",
                      "ios/events/KeyboardEventEmitterPayload.swift",
                      "ios/extensions/CGFloat.swift",
                      "ios/extensions/Date.swift",
                      "ios/extensions/NSObject.swift",
                      "ios/extensions/Notification.swift",
                      "ios/extensions/String.swift",
                      "ios/extensions/UIApplication.swift",
                      "ios/extensions/UIKeyboardType.swift",
                      "ios/extensions/UIResponder.swift",
                      "ios/extensions/UIScrollView.swift",
                      "ios/extensions/UITextInput.swift",
                      "ios/extensions/UIView.swift",
                      "ios/extensions/UIWindow.swift",
                      "ios/interactive/InvisibleInputAccessoryView.swift",
                      "ios/interactive/KeyboardAreaExtender.swift",
                      "ios/interactive/KeyboardOffsetProvider.swift",
                      "ios/observers/FocusedInputObserver.swift",
                      "ios/observers/movement/KeyboardEventsIgnorer.swift",
                      "ios/observers/movement/KeyboardTrackingView.swift",
                      "ios/observers/movement/KeyboardViewLocator.swift",
                      "ios/observers/movement/observer/KeyboardMovementObserver+Animation.swift",
                      "ios/observers/movement/observer/KeyboardMovementObserver+Interactive.swift",
                      "ios/observers/movement/observer/KeyboardMovementObserver+Lifecycle.swift",
                      "ios/observers/movement/observer/KeyboardMovementObserver+Listeners.swift",
                      "ios/observers/movement/observer/KeyboardMovementObserver+Watcher.swift",
                      "ios/observers/movement/observer/KeyboardMovementObserver.swift",
                      "ios/protocols/TextInput.swift",
                      "ios/swizzling/UIResponderSwizzle.swift",
                      "ios/traversal/FocusedInputHolder.swift",
                      "ios/traversal/KeyboardView.swift",
                      "ios/traversal/ViewHierarchyNavigator.swift",
                      "ios/views/KeyboardControllerViewManager.swift",
                      "ios/views/KeyboardExtenderContainerView.swift"
            ],
            linkerSettings: [
                .linkedFramework("UIKit"),
                .linkedFramework("Foundation"),
            ]
        ),
        .target(
            name: "ReactNativeKeyboardControllerObjC",
            dependencies: reactHeaders + ["ReactNativeKeyboardControllerSwift"],
            path: ".",
            sources: [
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCClippingScrollViewDecoratorViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardBackgroundViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardControllerViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardExtenderState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardGestureAreaState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCKeyboardToolbarGroupViewState.h",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewComponentDescriptor.h",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewShadowNode.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewShadowNode.h",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewState.cpp",
                "common/cpp/react/renderer/components/RNKC/RNKCOverKeyboardViewState.h",
                "ios/KeyboardController-Bridging-Header.h",
                "ios/KeyboardControllerModule-Header.h",
                "ios/KeyboardControllerModule.mm",
                "ios/events/FocusedInputLayoutChangedEvent.h",
                "ios/events/FocusedInputLayoutChangedEvent.m",
                "ios/events/FocusedInputSelectionChangedEvent.h",
                "ios/events/FocusedInputSelectionChangedEvent.m",
                "ios/events/FocusedInputTextChangedEvent.h",
                "ios/events/FocusedInputTextChangedEvent.m",
                "ios/events/KeyboardMoveEvent.h",
                "ios/events/KeyboardMoveEvent.m",
                "ios/objc/NSObject+SafeKVC.h",
                "ios/objc/NSObject+SafeKVC.m",
                "ios/objc/RCTUIManager+LayoutAnimationManager.h",
                "ios/objc/RCTUIManager+LayoutAnimationManager.m",
                "ios/objc/TextInput+DelegateManager.h",
                "ios/objc/TextInput+DelegateManager.m",
                "ios/views/ClippingScrollViewDecoratorViewManager.h",
                "ios/views/ClippingScrollViewDecoratorViewManager.mm",
                "ios/views/KeyboardBackgroundViewManager.h",
                "ios/views/KeyboardBackgroundViewManager.mm",
                "ios/views/KeyboardControllerView.h",
                "ios/views/KeyboardControllerView.mm",
                "ios/views/KeyboardControllerViewManager.mm",
                "ios/views/KeyboardExtenderManager.h",
                "ios/views/KeyboardExtenderManager.mm",
                "ios/views/KeyboardGestureAreaManager.h",
                "ios/views/KeyboardGestureAreaManager.mm",
                "ios/views/KeyboardToolbarGroupViewManager.h",
                "ios/views/KeyboardToolbarGroupViewManager.mm",
                "ios/views/OverKeyboardViewManager.h",
                "ios/views/OverKeyboardViewManager.mm",
            ],
            publicHeadersPath: "ios",
            cSettings: [
                .headerSearchPath("ios"),
                .headerSearchPath("."),
                .unsafeFlags(["-include", "react-native-spm-prefix.h"]),
            ],
            cxxSettings: [
                .headerSearchPath("ios"),
                .headerSearchPath("."),
                .unsafeFlags(["-include", "react-native-spm-prefix.h"]),
                .define("DEBUG", .when(configuration: .debug)),
                .define("NDEBUG", .when(configuration: .release)),
            ],
            linkerSettings: [
                .linkedFramework("UIKit"),
                .linkedFramework("Foundation"),
                .linkedFramework("CoreGraphics"),
            ]
        ),
    ],
    swiftLanguageModes: [.v5],
    cxxLanguageStandard: .cxx20
)
