export enum ScreenNames {
  ANIMATED_EXAMPLE = 'ANIMATED_EXAMPLE',
  REANIMATED_CHAT = 'REANIMATED_CHAT',
  EVENTS = 'EVENTS',
  AWARE_SCROLL_VIEW = 'AWARE_SCROLL_VIEW',
  STATUS_BAR = 'STATUS_BAR',
  EXAMPLES_STACK = 'EXAMPLES_STACK',
  EXAMPLES = 'EXAMPLES',
  NON_UI_PROPS = 'NON_UI_PROPS',
  INTERACTIVE_KEYBOARD = 'INTERACTIVE_KEYBOARD',
  INTERACTIVE_KEYBOARD_IOS = 'INTERACTIVE_KEYBOARD_IOS',
  NATIVE_STACK = 'NATIVE_STACK',
}
