export enum ScreenNames {
  ANIMATED_EXAMPLE = 'ANIMATED_EXAMPLE',
  REANIMATED_CHAT = 'REANIMATED_CHAT',
  EVENTS = 'EVENTS',
  AWARE_SCROLL_VIEW = 'AWARE_SCROLL_VIEW',
  STATUS_BAR = 'STATUS_BAR',
  INTERACTIVE_KEYBOARD = 'INTERACTIVE_KEYBOARD',
  EXAMPLES_STACK = 'EXAMPLES_STACK',
  EXAMPLES = 'EXAMPLES',
}
