#pragma once

#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

/**
 * Note this import and that it is not present in autogenerated header file
 * under android/build/generated/source/codegen/jni/keyboardcontroller.h
 *
 * Here we are overriding autogenerated component descriptors by prioritizing our custom headers via include path setup.
 */
#include <react/renderer/components/keyboardcontroller/RNKCKeyboardControllerViewComponentDescriptor.h>
#include <react/renderer/components/keyboardcontroller/RNKCKeyboardGestureAreaComponentDescriptor.h>
#include <react/renderer/components/keyboardcontroller/RNKCOverKeyboardViewComponentDescriptor.h>
#include <react/renderer/components/keyboardcontroller/RNKCKeyboardBackgroundViewComponentDescriptor.h>

#include <memory>
#include <string>

namespace facebook::react {
  JSI_EXPORT
  std::shared_ptr<TurboModule> keyboardcontroller_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params);
} // namespace facebook::react
