#pragma once

#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

/**
 * Note this import and that it is not present in autogenerated header file
 * under android/build/generated/source/codegen/jni/rnkc.h
 *
 * Here we are overriding autogenerated component descriptors by prioritizing our custom headers via include path setup.
 */
#include <react/renderer/components/rnkc/RNKCKeyboardControllerViewComponentDescriptor.h>
#include <react/renderer/components/rnkc/RNKCKeyboardGestureAreaComponentDescriptor.h>
#include <react/renderer/components/rnkc/RNKCOverKeyboardViewComponentDescriptor.h>
#include <react/renderer/components/rnkc/RNKCKeyboardBackgroundViewComponentDescriptor.h>

#include <memory>
#include <string>

namespace facebook::react {
JSI_EXPORT
std::shared_ptr<TurboModule> rnkc_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params);
} // namespace facebook::react
