name: 🌐 Publish Package to npmjs

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          # ⚠️ Do not use any cache on purpose
          # It increases the chance of a compromised release being publish
          # See https://github.com/actions/setup-node/issues/1445#issuecomment-4040130833
          # cache: yarn
          package-manager-cache: false
      - run: yarn install --frozen-lockfile
      - run: npm publish --provenance
