name: Validate Kotlin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Kotlin Lint
    steps:
      - uses: actions/checkout@v2
      - uses: touchlab-lab/ktlint-action-setup@1.0.0
        with:
          ktlint_version: 0.45.2
      - run: ktlint "android/src/**/*.kt"
